### 1. What is a Python library? Why do we use Python libraries?

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

A Python library is a collection of pre-written code and functions that can be imported and used in your Python program. Libraries provide a set of tools and resources to perform specific tasks without having to write the code from scratch. These libraries are developed and shared by the Python community to promote code reuse and make development more efficient.

There are various reasons why we use Python libraries:

1. **Code Reusability**: Libraries contain pre-written code that can be reused in different projects, saving time and effort. This promotes modular and maintainable code.

2. **Functionality**: Libraries provide additional functionality that may not be available in the core Python language. They extend the capabilities of Python and allow developers to perform a wide range of tasks without having to implement everything manually.

3. **Efficiency**: Using well-established libraries can lead to more efficient and optimized code. Experienced developers have contributed to these libraries, ensuring they are well-tested and performant.

4. **Community Support**: Popular libraries have a large community of developers who contribute to their improvement and provide support. This means you can benefit from the collective knowledge and experience of the community.

5. **Specialized Tasks**: There are libraries designed for specific domains or tasks, such as data analysis, machine learning, web development, and more. These libraries often include tools and algorithms tailored to their respective fields.

6. **Interoperability**: Python libraries often integrate seamlessly with other technologies, making it easier to use Python in conjunction with other programming languages or systems.

7. **Rapid Development**: By leveraging existing libraries, developers can speed up the development process, focusing on higher-level logic rather than dealing with low-level details.


### 2. What is the difference between Numpy array and List?

In [2]:
my_list = [1, 2, 3, 4, 5]
my_list_squared = [x**2 for x in my_list]
print(my_list_squared)

# Using NumPy arrays
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
my_array_squared = my_array**2
print(my_array_squared)

[1, 4, 9, 16, 25]
[ 1  4  9 16 25]


While lists are more flexible and versatile, NumPy arrays are designed for numerical operations and offer better performance, memory efficiency, and a wide range of mathematical functions. The choice between them depends on the specific requirements of your task.

NumPy arrays and Python lists are both used to store and manipulate collections of items, but there are several key differences between them:

1. **Data Type:**

   1.1. **List**: Python lists can contain elements of different data types. You can have a mix of integers, floats, strings, and other types within a single list.

   1.2. **NumPy Array**: NumPy arrays are homogeneous, meaning all elements must be of the same data type. This allows for more efficient storage and operations on the data.

2. **Performance:**

   2.1. **List**: Lists are generally less efficient in terms of performance compared to NumPy arrays, especially when dealing with large datasets or numerical computations.

   2.2. **NumPy Array**: NumPy arrays are implemented in C and are more compact in memory. They provide better performance for numerical operations due to their fixed data type and efficient memory layout.

3. **Size:**

   3.1. **List**: Lists are more flexible in size, and you can easily append or remove elements.

   3.2. **NumPy Array**: NumPy arrays have a fixed size when created. Changing the size involves creating a new array, and therefore operations like appending or removing elements are less flexible.

4. **Functionality:**

   4.1. **List**: Lists provide a variety of general-purpose methods and operations. However, for numerical operations, you may need to use loops, which can be less efficient for large datasets.

   4.2. **NumPy Array**: NumPy arrays come with a wide range of mathematical functions and operations that are optimized for performance. This makes them particularly suitable for numerical computations and scientific computing.

5. **Syntax:**

   5.1. **List**: Lists are part of the core Python language and have a simple syntax. They are created using square brackets, e.g., `my_list = [1, 2, 3]`.

   5.2. **NumPy Array**: NumPy arrays are created using the `numpy.array()` function, and the syntax is slightly different, e.g., `my_array = numpy.array([1, 2, 3])`.


### 3. Find the shape, size and dimension of the following array?
```python
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

shape = arr.shape
size = arr.size
dimension = arr.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)

Shape: (3, 4)
Size: 12
Dimension: 2


### 4. Write python code to access the first row of the following array?
```python
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

first_row = arr[0, :]

print(first_row)

[1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?
```python
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

element = arr[2, 3]

print(element)

12


### 6. Write code to extract all odd-indexed elements from the given numpy array?
```python
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]

print(odd_indexed_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [7]:

import numpy as np

random_matrix = np.random.rand(3, 3)

print(random_matrix)

[[0.2413283  0.7532022  0.35912867]
 [0.24866334 0.25399349 0.56991404]
 [0.36064449 0.03646373 0.99018375]]


### 8. Describe the difference between np.random.rand and np.random.randn? np.random.rand generates random values from a uniform distribution over [0, 1)

In [8]:

random_matrix_uniform = np.random.rand(3, 3)
print(random_matrix_uniform)

# np.random.randn generates random values from a standard normal distribution (mean=0, std=1)
random_matrix_normal = np.random.randn(3, 3)
print(random_matrix_normal)

[[0.16824405 0.42020629 0.8188254 ]
 [0.67543577 0.92694825 0.88515035]
 [0.42405236 0.70294786 0.18697717]]
[[ 0.94980974 -1.05115249  0.15399706]
 [ 0.12783998  0.08034937  0.71807079]
 [-1.75369136  0.0341414   2.2481236 ]]


### 9. Write code to increase the dimension of the following array?
```python
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

increased_dimension = np.expand_dims(arr, axis=0)

print(increased_dimension)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


### 10. How to transpose the following array in NumPy?
```python
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

transposed_array = np.transpose(arr)

print(transposed_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consider the following matrix:
### Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### 11.1. Index wise multiplication
### 11.2. Matrix multiplication
### 11.3. Add both the matrix
### 11.4. Subtract matrix B from A 
### 11.5. Divide Matrix B by A

In [11]:
import numpy as np

# Matrix A
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Matrix B
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = A * B

# 2. Matrix multiplication
matrix_multiplication = np.dot(A, B.T)

# 3. Add both the matrix
matrix_addition = A + B

# 4. Subtract matrix B from A
matrix_subtraction = A - B

# 5. Divide Matrix B by A
matrix_division = np.divide(B, A)

print("1. Index wise multiplication:\n", index_wise_multiplication)
print("\n2. Matrix multiplication:\n", matrix_multiplication)
print("\n3. Matrix addition:\n", matrix_addition)
print("\n4. Matrix subtraction:\n", matrix_subtraction)
print("\n5. Matrix division:\n", matrix_division)

1. Index wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Matrix division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12. Which function in Numpy can be used to swap the byte order of an array?


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype=np.int32)

swapped_arr = arr.byteswap()

print(swapped_arr)

[16777216 33554432 50331648 67108864]


### 13. What is the significance of the np.linalg.inv function?

In [13]:
import numpy as np

# Example code for np.linalg.inv
A = np.array([[1, 2], [3, 4]])

# Calculating the inverse of matrix A
A_inv = np.linalg.inv(A)

print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


### 14. What does the np.reshape function do, and how is it used?

In [14]:
import numpy as np

# Example code for np.reshape
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the array to a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


### 15. What is broadcasting in Numpy?

In [15]:
import numpy as np

# Example code for broadcasting
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])

# Broadcasting - Adding a 1D array to a 2D array
result = A + B

print(result)

[[11 22 33]
 [14 25 36]]
